language: perl
perl:
    #- dev
    - "blead"
    #- stable
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8.8"
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - sudo apt-get update
  - sudo apt-get install rdfind symlinks
  - cpan-install autodie DateTime File::Find::Rule File::pushd Getopt::Long IPC::System::Simple List::Util Locale::Country~3.11 Net::FTP Parallel::ForkManager Params::Validate Path::Class
  - perl ./tools/update-from-latest-olson --notests
  - cpan-install ExtUtils::MakeMaker~6.68 --deps
script:
  - perl Makefile.PL
  - make
  - prove -br -j$(test-jobs) $(test-files)
